version: "3.8"
services:
  # Service front-end Svelte
  front:
    container_name: frontend_pile_oh_poil
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    restart: always
    networks:
      - network-app

  # Service back-end Express  
  back:
    container_name: backend_pile_oh_poil
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - network-app
    restart: always

  # Service base de données MySQL
  db:
    container_name: database_pile_oh_poil
    image: mysql:8.0
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network-app
    restart: always

  # Service PHPMyAdmin
  phpmyadmin:
    container_name: phpmyadmin_pile_oh_poil
    image: phpmyadmin/phpmyadmin
    # env_file:
    #   - .env.development
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - network-app
    restart: always

  # Service base de données PostgreSQL pour Umami
  umami_db:
    container_name: umami_database_pile_oh_poil
    image: postgres:13
    env_file:
      - .env.development
    volumes:
      - umami_db_data:/var/lib/postgresql/data
    networks:
      - network-app
    restart: always

  # Service Umami Analytics
  umami:
    container_name: umami_pile_oh_poil
    image: docker.umami.is/umami-software/umami:postgresql-latest
    env_file:
      - .env.development
    ports:
      - "3001:3000"  # Expose Umami sur le port 3001
    depends_on:
      - umami_db
    networks:
      - network-app
    restart: always

volumes:
  db_data:
  umami_db_data:

networks:
  network-app:
    driver: bridge
